repo_root <- normalizePath(".", mustWork = TRUE)
rscript <- file.path(R.home("bin"), if (.Platform$OS.type == "windows") "Rscript.exe" else "Rscript")
script <- file.path(repo_root, "scripts", "compare_spatial_support.R")
output <- system2(rscript, c(shQuote(script), "--help"), stdout = TRUE, stderr = TRUE)
status <- attr(output, "status")
if (!is.null(status) && status != 0) stop("compare_spatial_support.R --help failed")
stopifnot(any(grepl("Usage: Rscript scripts/compare_spatial_support.R", output, fixed = TRUE)))
stopifnot(any(grepl("--include-dynamic", output, fixed = TRUE)))
cat("Spatial support comparison help regression test passed\n")
