repo_root <- normalizePath(".", mustWork = TRUE)
model_path <- file.path(repo_root, "outputs", "preprocessing_demo", "model_inputs.rds")
if (!file.exists(model_path)) stop("Run scripts/run_preprocessing_demo.R first.")
inputs <- readRDS(model_path)
stopifnot(!is.null(inputs$mesh), inputs$mesh$n > 0)
stopifnot(nrow(inputs$mesh_polygons) == inputs$mesh$n)
stopifnot(!anyDuplicated(inputs$mesh_polygons$poly_id), all(inputs$mesh_polygons$area_km2 > 0))
stopifnot(!anyDuplicated(inputs$time_index$time_index))
stopifnot(all(!is.na(inputs$tier1$time_index)), all(!is.na(inputs$tier2$time_index)))
stopifnot(sum(inputs$tier1$Yi == 1) + nrow(inputs$excluded_tier1_positives) == inputs$observation_audit$count[inputs$observation_audit$stage == "retained"])
stopifnot("outside_analysis_domain" %in% inputs$observation_audit$stage)
stopifnot(all(inputs$tier2$count >= 0), sum(inputs$tier2$count) == inputs$preprocessing_metadata$detection_conservation$tier2_count)
stopifnot(inputs$preprocessing_metadata$detection_conservation$model_eligible_detections == inputs$preprocessing_metadata$detection_conservation$tier2_count)
stopifnot(nrow(inputs$covariate_audit) >= 11)
stopifnot(!is.null(inputs$transformations), inputs$transformations$type == "training_only")
stopifnot(inputs$thinning_audit$input_positive_count == inputs$thinning_audit$retained_positive_count + inputs$thinning_audit$excluded_positive_count)
stopifnot(all(nzchar(inputs$excluded_detections$exclusion_reason)))
required <- c("mintemp_z", "soilmoist_z", "leafarea_z", "rhum_z", "northing_z", "tmin_hinge")
stopifnot(all(required %in% names(inputs$tier2)), all(required %in% names(inputs$prediction_grid)))
stopifnot(!anyDuplicated(inputs$prediction_grid$space_time_id))
weeks_per_cell <- table(inputs$prediction_grid$cell_id)
stopifnot(all(weeks_per_cell == nrow(inputs$time_index)))
stopifnot(length(unique(inputs$tier2$mintemp)) > 1, length(unique(inputs$prediction_grid$cattle)) > 1)
message("Preprocessing demo smoke checks passed: ", inputs$mesh$n, " mesh vertices; ", length(weeks_per_cell), " prediction cells; ", nrow(inputs$time_index), " weeks.")
