clean_host_values <- function(x) stringr::str_replace_all(tolower(trimws(as.character(x))), "[^a-z]", "")
read_observations <- function(path) { if (!file.exists(path)) stop("Observation file not found: ", path); readr::read_csv(path, show_col_types = FALSE) }
read_host_lookup <- function(path) { x <- readr::read_csv(path, show_col_types = FALSE); require_columns(x, c("host_cleaned", "host_standardized", "host_group", "multiple_host_flag"), "host lookup"); x }
preprocess_observations <- function(observations, boundary, cfg, host_lookup) {
  require_columns(observations, c("date", "lon", "lat", "host"), "observations"); audit <- data.frame(stage = "input", before = nrow(observations), after = nrow(observations), excluded = 0, reason = NA_character_); x <- observations; x$obs_id <- seq_len(nrow(x)); x$host_raw <- as.character(x$host); x$date <- as.Date(x$date)
  n <- sum(is.na(x$date)); audit <- audit_row_change(audit, "valid_date", nrow(x), nrow(x)-n, "invalid_or_missing_date"); x <- x[!is.na(x$date), ]; keep <- x$date >= as.Date(cfg$study$start_date) & x$date <= as.Date(cfg$study$end_date); audit <- audit_row_change(audit, "study_period", nrow(x), sum(keep), "outside_study_period"); x <- x[keep, ]; valid_xy <- is.finite(x$lon) & is.finite(x$lat) & x$lon >= -180 & x$lon <= 180 & x$lat >= -90 & x$lat <= 90; audit <- audit_row_change(audit, "valid_coordinates", nrow(x), sum(valid_xy), "invalid_or_missing_coordinates"); x <- x[valid_xy, ]
  pts <- sf::st_transform(sf::st_as_sf(x, coords = c("lon", "lat"), crs = 4326, remove = FALSE), sf::st_crs(boundary)); inside <- lengths(sf::st_within(pts, boundary)) > 0; audit <- audit_row_change(audit, "analysis_domain", nrow(x), sum(inside), "outside_spatial_domain"); x <- x[inside, , drop = FALSE]; xy <- sf::st_coordinates(pts[inside, , drop = FALSE]); x$x <- xy[,1]; x$y <- xy[,2]; x$epiyear <- lubridate::isoyear(x$date); x$epiweek <- lubridate::isoweek(x$date); x$location_date_key <- paste(x$date, x$x, x$y, sep = "|"); audit <- audit_row_change(audit, "duplicate_rule", nrow(x), sum(!duplicated(x$location_date_key)), "exact_same_date_location_keep_first"); x <- x[!duplicated(x$location_date_key), , drop = FALSE]
  x$host_cleaned <- clean_host_values(x$host_raw); x <- dplyr::left_join(x, host_lookup, by = "host_cleaned"); x$host_standardized[is.na(x$host_standardized)] <- "unknown"; x$host_group[is.na(x$host_group)] <- "unknown"; x$multiple_host_flag[is.na(x$multiple_host_flag)] <- FALSE; time <- make_week_index(cfg$study$start_date, cfg$study$end_date); x <- dplyr::left_join(x, time, by = c("epiyear", "epiweek")); audit <- rbind(audit, data.frame(stage = "retained", before = nrow(observations), after = nrow(x), excluded = nrow(observations)-nrow(x), reason = "all_documented_rules")); list(data = x, audit = audit, unmapped_hosts = sort(unique(x$host_cleaned[!x$host_cleaned %in% host_lookup$host_cleaned])))
}
